import { Button, Card, Classes, Dialog } from '@blueprintjs/core';
import * as React from 'react';
import Dropzone from 'react-dropzone';
import aldisLogo from '../../aldis-logo.png';
import './IntroductionPanel.css';

export interface IntroductionPanelProps {
  style?: React.CSSProperties
  onFileSelected: (file:File) => void
}

interface IntroductionPanelState {
  supportedFormatDialogVisible: boolean
}

export class IntroductionPanel extends React.Component<IntroductionPanelProps, IntroductionPanelState> {
  private onDrop: (acceptedFiles: File[])=>void

  constructor(props:IntroductionPanelProps) {
    super(props)
    this.onDrop = this._onDrop.bind(this)
    this.state = { supportedFormatDialogVisible: false }
  }

  public render() {
    return (
      <Card elevation={2} className="intro-panel" style={this.props.style}>
        <div className='intro-logo'>
          <img src={ aldisLogo }/>
        </div>
        <div className='intro-text'>
          <h3>Welcome to Charted Sails!</h3>
          <p>
            To begin, select one of the demo trips on the map or drag and drop one of your own log files.
          </p>
          <Dropzone onDrop={ this.onDrop } className='dropzone'
            acceptClassName='dropzoneAccept' rejectClassName='dropzoneReject' >
            <p>Try dropping some files here, or click to select files to upload.</p>
          </Dropzone>
          <p>
            <Button icon="info-sign" minimal={true} onClick={ () => this.setState({ supportedFormatDialogVisible: true }) }>
              Who are you? What is this? What logs?
            </Button>
          </p>
          <Dialog icon="info-sign" onClose={ () => this.setState({ supportedFormatDialogVisible: false }) }
            title="About Charted Sails" isOpen={ this.state.supportedFormatDialogVisible }>
            <div className={Classes.DIALOG_BODY}>
              <p>
                <strong>
                  Visualize, Analyze and Share your sailing log files.
                </strong>
              </p>
              <p>
                <h2>Supported Formats</h2>
                <ul>
                  <li>SignalK log files, generated by the <a target="_blank"
                    href="https://github.com/SignalK/signalk-server-node">SignalK server</a> or by <a
                    href="https://www.tindie.com/products/sarfata/kbox-open-source-boat-gateway/?utm_source=chartedsails&amp;utm_medium=link"
                    target="_blank" >KBox</a>.<br/>
                    These files contain everything measured by your boat instruments and are by far the most detailed logs.
                  </li>
                  <li><a target="_blank" href="https://www.expeditionmarine.com/?utm_source=chartedsails&amp;utm_medium=link">Expedition
                  </a> log files (CSV files).<br/>Also a very rich and detailed format.</li>
                  <li><a target="_blank" href="https:/velocitek.com/?utm_source=chartedsails&amp;utm_medium=link">Velocitek
                  </a> log files in VCC format.<br/>
                  Usually Contains position, time, true heading and speed over ground.</li>
                  <li>GPX tracks exported from iNavX, Garmin inReach or Velocitek. (Depending on the software generating the file
                    you will be limited to time and position; iNavX also records speed and course over ground).
                  </li>
                  <li><i>Your format here</i>: We would love to add support more formats. Email us and send us
                  sample log files so we can add them.</li>
                </ul>
                <h2>Work in progress</h2>
                Charted Sails is very much a work in progress, recently started (Summer 2018) and we would love to hear from you!<br/>
                What features would you like to see? How would you like to use this? <a
                href="mailto:hello@chartedsails.com">Let us know!</a>
                <h2>Privacy</h2>
                We take your privacy very seriously! When you open a logfile on Charted Sails the data stays on your
                computer and is not transmitted to anyone.<br/>
                We do use analytics to measure interest and usage of this service. In these analytics we collect the file name
                of your logfiles so we can identify the most popular formats. It's the only piece of information sent to us.
                <h2>Contact Information</h2>
                Charted Sails is developed by Thomas Sarlandie. You can reach out via email to <a
                href="mailto:hello@chartedsails.com">hello@chartedsails.com</a> - or come say hi on the <a
                href="http://slack-invite.signalk.org/" target="_blank">SignalK Slack server</a>, I am 'sarfata' over there.
              </p>
            </div>
          </Dialog>
        </div>
      </Card>
    )
  }

  private _onDrop(files: File[]) {
    if (files.length !== 1) {
      console.log(`Interesting, user dropped ${files.length} files.`)
    }
    this.props.onFileSelected(files[0])
  }
}